cognitive-complexity-threshold = 25
type-complexity-threshold = 100
single-char-binding-names-threshold = 1
too-many-arguments-threshold = 5
too-many-lines-threshold = 80
trivial-copy-size-limit = 32
pass-by-value-size-limit = 64
too-large-for-stack = 200
vec-box-size-threshold = 4096
enum-variant-size-threshold = 200
max-struct-bools = 3
max-fn-params-bools = 3
unreadable-literal-lint-fractions = true
upper-case-acronyms-aggressive = true
avoid-breaking-exported-api = true
msrv = "1.85.0"
missing-docs-in-crate-items = true
allow-private-module-inception = false
suppress-restriction-lint-in-const = false
check-private-items = true
arithmetic-side-effects-allowed = []
arithmetic-side-effects-allowed-binary = []
arithmetic-side-effects-allowed-unary = []