[server]
host = "0.0.0.0"
port = 8080

[database]
url = "postgresql://sdrtrunk:sdrtrunk_dev_password@localhost:5432/sdrtrunk_transcriber"
max_connections = 50


[storage]
base_dir = "/tmp/sdrtrunk"
upload_dir = "uploads"
max_file_size = 104857600

[api]
enable_auth = false

[security]
require_api_key = false

[logging]
level = "info"
format = "json"

[monitor]
watch_dir = "/tmp/sdrtrunk/watch"
archive_dir = "/tmp/sdrtrunk/archive"
failed_dir = "/tmp/sdrtrunk/failed"
temp_dir = "/tmp/sdrtrunk/temp"