# SDRTrunk Transcriber Configuration
# Copy this file to config.toml and update with your values

[server]
# API server binding configuration
host = "0.0.0.0"
port = 8080

[webserver]
host = "0.0.0.0"
port = 9000
workers = 4

[database]
# PostgreSQL connection string
# Update with your database credentials
url = "postgresql://username:password@localhost:5432/sdrtrunk_transcriber"
max_connections = 50

[storage]
# Base directory for all file storage
base_dir = "/tmp/sdrtrunk"
upload_dir = "uploads"
max_file_size = 104857600  # 100MB in bytes

[api]
# API authentication settings
enable_auth = false

[security]
# Require API key for all requests
require_api_key = false

[logging]
# Log level: trace, debug, info, warn, error
level = "info"
# Log format: json, compact, pretty, full
format = "json"

[monitor]
# Directory monitoring configuration
watch_dir = "/tmp/sdrtrunk/watch"     # Directory to watch for new files
archive_dir = "/tmp/sdrtrunk/archive" # Successfully processed files
failed_dir = "/tmp/sdrtrunk/failed"   # Failed processing files
temp_dir = "/tmp/sdrtrunk/temp"       # Temporary processing directory

[transcription]
# Transcription service configuration
enabled = true
service = "whisperx"                  # Service type: whisperx, mock
service_port = 8002                   # WhisperX service port
model_size = "large-v3"               # Model size: tiny, base, small, medium, large, large-v2, large-v3
device = "cpu"                        # Device: cpu, cuda, mps
compute_type = "int8"                 # Compute type: int8, float16, float32
batch_size = 8                        # Batch size for processing
workers = 2                           # Number of worker threads
queue_size = 500                      # Maximum queue size
timeout_seconds = 300                 # Processing timeout in seconds
language = "en"                       # Language code (e.g., en, es, fr)

# IMPORTANT: Get your token from https://huggingface.co/settings/tokens
# This token is required for speaker diarization models
hf_token = "YOUR_HF_TOKEN_HERE"

# VAD (Voice Activity Detection)
vad_filter = true                     # Enable Silero VAD for speech detection
vad_onset = 0.5                       # Speech start detection threshold
vad_offset = 0.35                     # Speech end detection threshold
chunk_length = 30                     # Length of audio chunks in seconds

# Decoding + fallback parameters
temperature = [0.0, 0.2, 0.4]         # Temperature fallback array (starts greedy, falls back to sampling)
beam_size = 5                         # Number of beams in beam search
best_of = 5                           # Number of candidates when sampling
patience = 1.2                        # Beam decoding patience factor
length_penalty = 1.0                  # Token length penalty coefficient
repetition_penalty = 1.2              # Penalty for repeated tokens
no_repeat_ngram_size = 3              # Prevent n-gram repetition

# Hallucination/silence guards
compression_ratio_threshold = 2.0     # Threshold for compression ratio heuristic
logprob_threshold = -1.0              # Average log probability threshold
no_speech_threshold = 0.5             # Probability threshold for no speech detection

# Context & timestamps
condition_on_previous_text = false    # Use previous text as context
without_timestamps = true             # WhisperX-native mode; alignment supplies word times
suppress_blank = true                 # Suppress blank outputs
suppress_tokens = "-1"                # Tokens to suppress (-1 = default list)

# Diarization (speaker identification)
diarization = true                    # Enable speaker diarization
min_speakers = 2                      # Minimum number of speakers (tighten if you know the channel)
max_speakers = 3                      # Maximum number of speakers
word_timestamps = true                # Extract word-level timestamps