# Rust toolchain specification for reproducible builds
# This ensures all developers and CI use the same Rust version

[toolchain]
channel = "1.89.0"
components = [
  "rustfmt",
  "clippy",
  "rust-src",
  "rust-analyzer",
  "llvm-tools"
]

# Specify targets for cross-compilation
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin", 
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",  # For WebAssembly targets
]

# Profile for different use cases
profile = "default"