# Rust toolchain specification for reproducible builds
# This ensures all developers and CI use the same Rust version

[toolchain]
# Use specific Rust version for reproducible builds
channel = "1.85.0"

# Specify components needed for development
components = [
    "rustfmt",      # Code formatting
    "clippy",       # Linting
    "rust-src",     # Source code for stdlib (needed for rust-analyzer)
    "rust-analyzer", # LSP server for IDE support
    "miri",         # Interpreter for detecting undefined behavior
    "llvm-tools-preview", # LLVM tools for coverage and profiling
]

# Specify targets for cross-compilation
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin", 
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",  # For WebAssembly targets
]

# Profile for different use cases
profile = "default"