---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdrtrunk-audio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 50Gi
